---
- hosts: all
  gather_facts: no
  tasks:
    - name: >
        Create temporary inventory for wm, 
        since opera requires internal envvars to access the target. 
        Need more examples to access static nodes without specifying them in the inventory file
      add_host:
        name: wm
        groups: wm
        ansible_host: "{{ wm_public_address }}"
        ansible_user: "{{ wm_username }}"
        ansible_ssh_private_key_file: "{{ wm_keypath }}"
        ansible_ssh_common_args: >
          -o IdentitiesOnly=yes
          -o BatchMode=yes
          -o UserKnownHostsFile=/dev/null
          -o StrictHostKeyChecking=no

- hosts: wm
  gather_facts: no
  tasks:
    - name: Prepare tensorflow gpu image, -F forces overwrite (next time, prepare the skyline-extractor singularity image, based on tensorflow)
      shell: singularity pull -F docker://tensorflow/tensorflow:1.11.0-gpu
      args:
        chdir: "{{ job_workspace }}"