---
- hosts: all
  become_user: root
  become: yes
  vars:
    pip_install_packages:
        - name: docker

  tasks:
    - name: Delete docker containers
      docker_container:
        name: "{{ host_name }}"
        force_kill: true
        keep_volumes: false
        state: absent

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker