---
- hosts: all
  become_user: root
  become: yes
  vars:
    pip_install_packages:
      - name: docker

  tasks:
    - name: Copy archive to container
      copy:
        src: /home/xopera/build
        dest: "/home/xopera/"

    - name: Load image from archive and push to a private registry
      block:
        - docker_image:
            name: "{{ image_name }}"
            load_path: "/home/xopera/build/{{ archive_name }}"
            source: load
        - docker_image:
            name: "{{ image_name }}"
            repository: "{{ registry_ip }}/{{ image_name }}"
            tag: latest
            push: yes
            source: local
            ca_cert: "/home/xopera/certs/ca.crt"
            client_cert: "/home/xopera/certs/image.docker.local.crt"
            client_key: "/home/xopera/certs/image.docker.local.key"

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker
