---
- hosts: all
  become_user: root
  become: yes
  vars:
    pip_install_packages:
      - name: docker

  tasks:
    - name: Remove image
      block:
        - docker_image:
            state: absent
            name: "{{ image_name }}"
            tag: latest
        - docker_image:
            state: absent
            name: xopera_rest
            tag: latest

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker