tosca_definitions_version: tosca_simple_yaml_1_0

node_types:
  my.nodes.VM.OpenStack:
    derived_from: tosca.nodes.Compute
    properties:
      name:
        type: string
        description: Name that should be given to the VM in OpenStack
      image:
        type: string
        description: OpenStack image id (image names are not accepted)
      flavor:
        type: string
        description: OpenStack flavor id (flavor names are not accepted)
      network:
        type: string
        description: OpenStack network id (network names are not accepted)
      security_groups:
        type: string
        description: OpenStack names of the security groups to which the instance should be added.Comma separated string.
      key_name:
        type: string
        description: OpenStack SSH key name that should be placed on the VM
    attributes:
      id:
        type: string
        description: OpenStack id of the VM
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        create:
          inputs:
            vm_name:  { default: { get_property: [ SELF, name     ] } }
            image:    { default: { get_property: [ SELF, image    ] } }
            flavor:   { default: { get_property: [ SELF, flavor   ] } }
            network:  { default: { get_property: [ SELF, network  ] } }
            security_groups:  { default: { get_property: [ SELF, security_groups  ] } }
            key_name: { default: { get_property: [ SELF, key_name ] } }
          implementation: playbooks/vm/create.yml
        delete:
          inputs:
            id: { default: { get_attribute: [ SELF, id ] } }
          implementation: playbooks/vm/delete.yml

  my.nodes.Nginx:
    derived_from: tosca.nodes.SoftwareComponent
    attributes:
      site_config_dir:
        type: string
        description: Location of nginx site configs
    capabilities:
      host:
        type: tosca.capabilities.Compute
        valid_source_types: [my.nodes.Nginx.Site]
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        create:
          implementation:
            primary: playbooks/nginx/install.yml
        delete:
          implementation:
            primary: playbooks/nginx/uninstall.yml

  my.nodes.Nginx.Site:
    derived_from: tosca.nodes.SoftwareComponent
    requirements:
      - host:
          capability: tosca.capabilities.Compute
          relationship: my.relationships.NginxSiteHosting


relationship_types:
  my.relationships.NginxSiteHosting:
    derived_from: tosca.relationships.HostedOn
    valid_target_types: [my.nodes.Nginx]
    interfaces:
      Configure:
        add_source:
          implementation:
            primary: playbooks/nginx/reload.yml


topology_template:
  node_templates:
    vm:
      type: my.nodes.VM.OpenStack
      properties:
        name: website_nginx-test
        image: centos7
        flavor: m1.medium
        network: orchestrator-net
        security_groups: default,sodalite-xopera-rest,sodalite-remote-access
        key_name: { get_input: xopera-key-name}

    nginx:
      type: my.nodes.Nginx
      requirements:
        - host: vm

    site:
      type: my.nodes.Nginx.Site
      requirements:
        - host: nginx
      interfaces:
        Standard:
          inputs:
            site_config_dir:
              get_attribute: [ SELF, nginx, site_config_dir ]
          create: playbooks/site/delete.yml


    site-new:
      type: my.nodes.Nginx.Site
      requirements:
        - host: nginx
      interfaces:
        Standard:
          inputs:
            site_config_dir:
              get_attribute: [ SELF, nginx, site_config_dir ]
          create: playbooks/site-new/create.yml
          delete: playbooks/site-new/delete.yml
