---
- hosts: all
  become_user: root
  become: yes
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - name: Create db container and connect to network
      docker_container:
        name: db_test
        auto_remove: yes
        image: "postgres"
        ports:
          - "5432:5432"
        exposed_ports:
          - "5432"
        volumes:
          - "$HOME/docker/volumes/postgres:/var/lib/postgresql/data"
        env:
          POSTGRES_PASSWORD: password

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker
