---
- hosts: all
  become_user: root
  become: yes
  vars:
    pip_install_packages:
      - name: docker
      - name: cryptography
      - name: pyOpenSSL

  tasks:
    - name: Create certs and storage folders
      block:
        - file:
            path: /home/xopera/restapi
            state: directory
        - file:
            path: /home/xopera/certs
            state: directory

    - name: Copy root CA files
      block:
        - copy:
            src: /home/xopera/certs/ca.crt
            dest: /home/xopera/certs/ca.crt
        - copy:
            src: /home/xopera/certs/ca.key
            dest: /home/xopera/certs/ca.key

    - name: Install root CA
      block:
        - command: cp /home/xopera/certs/ca.crt /etc/pki/ca-trust/source/anchors/ca.crt
        - command: update-ca-trust

    - name: Generate certificates and clean up
      block:
        - openssl_privatekey:
            path: /home/xopera/certs/xopera.local.key
            size: 4096
        - openssl_csr:
            path: /home/xopera/certs/xopera.local.csr
            privatekey_path: /home/xopera/certs/xopera.local.key
            country_name: SI
            organization_name: XLAB
            email_address: dragan.radolovic@xlab.si
            common_name: xopera.local
            subject_alt_name: "IP:{{ public_ipv4_address }}"
        - openssl_certificate:
            path: /home/xopera/certs/xopera.local.crt
            csr_path: /home/xopera/certs/xopera.local.csr
            ownca_path: /home/xopera/certs/ca.crt
            ownca_privatekey_path: /home/xopera/certs/ca.key
            provider: ownca
        - file:
            state: absent
            path: "/home/xopera/certs/xopera.local.csr"

    - name: Generate OpenStack key
      block:
        - file:
            path: "/root/.ssh/"
            state: directory

        - openssl_privatekey:
            path: "/root/.ssh/{{ public_ipv4_address }}-xOpera.pk"
            size: 4096
        - openssl_publickey:
            path: "/root/.ssh/{{ public_ipv4_address }}-xOpera.pubk"
            format: OpenSSH
            privatekey_path: "/root/.ssh/{{ public_ipv4_address }}-xOpera.pk"

    - name: Install certificates for communication with the registry
      block:
        - file:
            path: /etc/docker/certs.d/{{ registry_ip }}
            state: directory
        - command: cp /home/xopera/certs/ca.crt /etc/docker/certs.d/{{ registry_ip }}
        - command: cp /home/xopera/certs/xopera.local.key /etc/docker/certs.d/{{ registry_ip }}
        - command: cp /home/xopera/certs/xopera.local.crt /etc/docker/certs.d/{{ registry_ip }}/xopera.local.cert

    - name: Set up the xOpera REST connector
      docker_container:
        name: xopera_rest
        restart_policy: always
        image: "{{ registry_ip }}/xopera_rest"
        ports:
          - "5000:5000"
        exposed_ports:
          - "5000"
        ca_cert: "/home/xopera/certs/ca.crt"
        client_cert: "/home/xopera/certs/xopera.local.crt"
        client_key: "/home/xopera/certs/xopera.local.key"
        etc_hosts:
          xopera.local: 127.0.0.1
        volumes:
          - "/home/xopera/restapi:/var/lib/restapi"
          - "/home/xopera/certs:/home/xopera/certs"
          - "/root/.ssh/:/root/.ssh/"

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker
