---
- hosts: all
  become_user: root
  become: yes
  vars:
    pip_install_packages:
      - name: docker
      - name: cryptography
      - name: pyOpenSSL
    imagepath: ""

  tasks:
    - name: Copy archived images to container
      copy:
        src: /home/xopera/build
        dest: "/home/xopera/"

    - name: Create certs and storage folders
      block:
        - file:
            path: "/home/xopera/drive"
            state: directory
        - file:
            path: "/home/xopera/certs"
            state: directory

    - name: Copy root CA files
      block:
        - copy:
            src: /home/xopera/certs/ca.crt
            dest: "/home/xopera/certs/ca.crt"
        - copy:
            src: /home/xopera/certs/ca.key
            dest: "/home/xopera/certs/ca.key"

    - name: Install root CA
      block:
        - command: "cp /home/xopera/certs/ca.crt /etc/pki/ca-trust/source/anchors/ca.crt"
        - command: update-ca-trust

    - name: Generate certificates and clean up
      block:
        - openssl_privatekey:
            path: "/home/xopera/certs/image.docker.local.key"
            size: 4096
        - openssl_csr:
            path: "/home/xopera/certs/image.docker.local.csr"
            privatekey_path: "/home/xopera/certs/image.docker.local.key"
            country_name: SI
            organization_name: XLAB
            email_address: dragan.radolovic@xlab.si
            common_name: "image.docker.local"
            subject_alt_name: "IP:{{ public_ipv4_address }}"
        - openssl_certificate:
            path: "/home/xopera/certs/image.docker.local.crt"
            csr_path: "/home/xopera/certs/image.docker.local.csr"
            ownca_path: "/home/xopera/certs/ca.crt"
            ownca_privatekey_path: "/home/xopera/certs/ca.key"
            provider: ownca
        - file:
            state: absent
            path: "/home/xopera/certs/image.docker.local.csr"

    - name: Generate OpenStack key
      block:
        - file:
            path: "/root/.ssh/"
            state: directory

        - openssl_privatekey:
            path: "/root/.ssh/{{ public_ipv4_address }}-xOpera.pk"
            size: 4096
        - openssl_publickey:
            path: "/root/.ssh/{{ public_ipv4_address }}-xOpera.pubk"
            format: OpenSSH
            privatekey_path: "/root/.ssh/{{ public_ipv4_address }}-xOpera.pk"

    - name: Install certificates for communication with the registry
      block:
        - file:
            path: "/etc/docker/certs.d/{{ registry_ip }}"
            state: directory
        - command: "cp /home/xopera/certs/ca.crt /etc/docker/certs.d/{{ registry_ip }}"
        - command: "cp /home/xopera/certs/image.docker.local.key /etc/docker/certs.d/{{ registry_ip }}"
        - command: "cp /home/xopera/certs/image.docker.local.crt /etc/docker/certs.d/{{ registry_ip }}/image.docker.local.cert"

    - name: Set up the image
      docker_container:
        name: "xopera"
        restart_policy: always
        image: "{{ registry_ip }}/{{ image }}"
        ports:
          - "{{ expose_port }}:{{ expose_port }}"
        exposed_ports:
          - "{{ expose_port }}"
        ca_cert: "/home/xopera/certs/ca.crt"
        client_cert: "/home/xopera/certs/image.docker.local.crt"
        client_key: "/home/xopera/certs/image.docker.local.key"
        etc_hosts:
          image.docker.local: 127.0.0.1
        volumes:
          - "/home/xopera/drive:/var/lib/xopera"
          - "/home/xopera/certs:/home/xopera/certs"
          - "/root/.ssh/:/root/.ssh/"
          - "/etc/docker/certs.d/{{ registry_ip }}:/etc/docker/certs.d/{{ registry_ip }}"
        env:
          DATABASE_IP: "{{ database_ip }}"

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker
