---
- hosts: all
  become_user: root
  become: yes
  vars:
    pip_install_packages:
        - name: docker

  tasks:

    - name: Delete docker containers
      docker_container:
        name: "xopera"
        force_kill: true
        keep_volumes: false
        state: absent

    - name: Remove folders with certs and storage
      block:
        - file:
            path: "/home/xopera/drive"
            state: absent
        - file:
            path: "/home/xopera/certs"
            state: absent
        - file:
            path: "/etc/docker/certs.d/{{ registry_ip }}"
            state: absent

    - name: Uninstall root CA
      block:
        - command: "rm -rf /etc/pki/ca-trust/source/anchors/ca.crt"
        - command: update-ca-trust

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker