tosca_definitions_version: tosca_simple_yaml_1_0

node_types:
   snow.nodes.DockerizedComponent:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      registry_ip:
        type: string
        description: IP of the docker registry
        required: false
        default: localhost
      image_name:
        type: string
        description: The name of the image on the host
        required: true
      ports:
        type: string
        description: Port binding for the docker container "exposed:internal" like "8081:8080"
        required: true
      exposed_ports:
        type: string
        description: Exposed ports of the container like "8081" 
        required: true
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        create:
          inputs:
            registry_ip:    { default: { get_property: [ SELF, registry_ip ] } }
            image_name:     { default: { get_property: [ SELF, image_name ] } }
            ports:          { default: { get_property: [ SELF, ports ] } }
            exposed_ports:  { default: { get_property: [ SELF, exposed_ports ] } }
          implementation:
            primary: playbooks/dockerized_component_deploy.yml
        delete:
          inputs:
            image_name:     { default: { get_property: [ SELF, image_name ] } }
            registry_ip:    { default: { get_property: [ SELF, registry_ip ] } }
          implementation:
            primary: playbooks/dockerized_component_undeploy.yml

topology_template:
  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    skyline-extractor:
      type: snow.nodes.DockerizedComponent
      properties:
        registry_ip: localhost
        image_name: snow-skyline-extractor
        ports: 8080:8080
        exposed_ports: 8080
      requirements:
        - host: my-workstation

    skyline-alignment:
      type: snow.nodes.DockerizedComponent
      properties:
        registry_ip: localhost
        image_name: snow-skyline-alignment
        ports: 8081:8080
        exposed_ports: 8081
      requirements:
        - host: my-workstation
