---
- name: Register audit statistics
  slurp:
    src: "{{ job_workspace_path }}/{{ job_name }}.stat"
  register: audit

- debug:
    msg: "{{ audit['content'] | b64decode | from_yaml }}"

- set_stats:
    data:
      audit: "{{ audit['content'] | b64decode | from_yaml }}"